export const FILTERS = {
  sort: {
    popular: "popular",
    price: "price",
    capacity: "capacity",
  },
  functions: {
    all: "all",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
  },
  energyClass: {
    all: "all",
    classA: "A",
    classB: "B",
    classD: "D",
  },
  capacity: {
    all: "all",
    small: 8,
    medium: 9,
    large: 10.5,
  },
};

export const TEXTS = {
  header: "Wybierz urządzenie",
  sort: "Sortuj po: ",
  functions: "Funkcje: ",
  energyClass: "Klasa energetyczna: ",
  capacity: "Pojemność: ",
  numOfItems: "Liczba wyników: ",
  showMore: "Pokaż więcej",
  item: {
    capacity: "Pojemność (kg): ",
    dimensions: "Wymiary (GxSxW): ",
    functions: "Funkcje: ",
    energyClass: "Klasa energetyczna",
    priceDate: "Cena obowiązuje: ",
    installments: " zł x 60 rat",
  },
  button: {
    clicked: "Wybrane",
    notClicked: "Wybierz",
  },
  filters: {
    sort: {
      all: "Popularność",
      price: "Cena",
      capacity: "Pojemność",
    },
    functions: {
      all: "Wszystkie",
      addWash: "Drzwi AddWash",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inwerterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: {
      all: "Wszystkie",
      classA: "A",
      classB: "B",
      classD: "D",
    },
    capacity: {
      all: "Wszystkie",
      small: "8kg",
      medium: "9kg",
      large: "10.5kg",
    },
  },
};

export const PRODUCTS = [
  {
    popularity: 1,
    code: "WW90T754ABT",
    type: "Pralka QuickDrive™",
    capacity: 8,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
    filters: ["addWash", "aiPanel", "inverterMotor", "screen"],
    functions: {
      addWash: "AddWash™",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "A",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 2199, gr: "00", currency: "zł" },
  },
  {
    popularity: 3,
    code: "WW10T654DLH",
    type: "Pralka QuickDrive™",
    capacity: 9,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
    filters: ["addWash", "aiPanel", "inverterMotor", "screen"],
    functions: {
      addWash: "AddWash™",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "B",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 3100, gr: "00", currency: "zł" },
  },
  {
    popularity: 2,
    code: "WW90T754ABT",
    type: "Pralka QuickDrive™",
    capacity: 10.5,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
    filters: ["addWash", "inverterMotor", "screen"],
    functions: {
      addWash: "AddWash™",
      aiPanel: "",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "D",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 3199, gr: "00", currency: "zł" },
  },
  {
    popularity: 3,
    code: "WW10T654DLH",
    type: "Pralka QuickDrive™",
    capacity: 9,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
    filters: ["aiPanel", "inverterMotor", "screen"],
    functions: {
      addWash: "",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "D",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 1800, gr: "00", currency: "zł" },
  },
  {
    popularity: 3,
    code: "WW10T654DLH",
    type: "Pralka QuickDrive™",
    capacity: 10.5,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "addWash",
    aiPanel: "aiPanel",
    inverterMotor: "inverterMotor",
    screen: "screen",
    filters: ["addWash", "aiPanel", "inverterMotor", "screen"],
    functions: {
      addWash: "AddWash™",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "A",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 4100, gr: "00", currency: "zł" },
  },
  {
    popularity: 3,
    code: "WW10T654DLH",
    type: "Pralka QuickDrive™",
    capacity: 8,
    color: "Biała",
    dimensions: "55 x 60 x 85 cm",
    addWash: "",
    aiPanel: "",
    inverterMotor: "inverterMotor",
    screen: "",
    filters: ["inverterMotor"],
    functions: {
      addWash: "AddWash™",
      aiPanel: "Panel AI Control",
      inverterMotor: "Silnik inverterowy",
      screen: "Wyświetlacz elektroniczny",
    },
    energyClass: "D",
    priceDate: "15.09.2022 - 21.09.2022",
    price: { zl: 3100, gr: "00", currency: "zł" },
  },
];
